//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRBook2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_UserInfo
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string RoleType { get; set; }
        public string Remark { get; set; }
        public string UserType { get; set; }
    }
}
