//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRBook2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pr_peopleinfo
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public long GetMoneyTimes { get; set; }
        public decimal GetMoneySum { get; set; }
        public long GiveMoneyTimes { get; set; }
        public decimal GiveMoneySum { get; set; }
        public string LastPr { get; set; }
        public System.DateTime InputDate { get; set; }
    }
}
